"use client";
export const fields = [
  [
    {
      name: "fullNameEnglish",
      label: "Full Name (English)",
      type: "text",
      elType: "text",
      placeholder: "Enter your first name",
      isRequired: true,
    },
    {
      name: "fullNameNepali",
      label: "Full Name (Nepali)",
      type: "nepaliInput",
      elType: "text",
      placeholder: "Enter your last name",
      isRequired: true,
    },
    {
      name: "gender",
      label: "Select Male/Female/Other",
      type: "select",
      elType: "select",
      options: ["Male", "Female", "Others"],
      placeholder: "Enter your gender",
      isRequired: true,
    },
    {
      name: "dobEnglish",
      label: "DOB in AD",
      type: "date",
      elType: "date",
      placeholder: "",
      isRequired: true,
    },
    {
      name: "dobNepali",
      label: "DOB in BS",
      type: "nepDate",
      elType: "nepDate",
      placeholder: "",
      isRequired: true,
    },
    {
      name: "phoneNumber",
      label: "Phone Number",
      type: "number",
      elType: "number",
      placeholder: "Enter your phone number",
      isRequired: true,
    },
  ],
  [
    {
      name: "district",
      label: "District",
      type: "select",
      elType: "select",
      options: ["Kathmandu", "Lalitpur", "Bhaktapur"],
      placeholder: "Enter your District",
      isRequired: true,
    },
    {
      name: "issuedDateAD",
      label: "Issued Date in AD",
      type: "date",
      elType: "date",
      placeholder: "",
      isRequired: true,
    },
    {
      name: "issuedDateBS",
      label: "Issued Date in BS",
      type: "nepDate",
      elType: "nepDate",
      placeholder: "",
      isRequired: true,
    },
    {
      name: "citizenshipFront",
      label: "Citizenship Front",
      type: "file",
      elType: "text",
      placeholder: "Required, validate image/pdf type and size 5MB",
      isRequired: true,
    },
    {
      name: "citizenshipBack",
      label: "Citizenship Back",
      type: "file",
      elType: "text",
      placeholder: "Required, validate image/pdf type and size 5MB",
      isRequired: true,
    },
  ],
];
